---
title: 'Translation control tunes *Drosophila* oogenesis'
author: 'Elliot T. Martin'
date: 'May 2022'
institution: 'University at Albany, State University of New York'
division: 'Biology'
advisor: 'Prashanth Rangan'
# If you have more two advisors, un-silence line 9
altadvisor: 'Gabriele Fuchs'
department: 'Biology'
degree: 'Doctor of Philosophy'
knit: bookdown::render_book
site: bookdown::bookdown_site

# This will automatically install the {remotes} package and {thesisdown}
# Change this to FALSE if you'd like to install them manually on your own.
params:
  'Install needed packages for {thesisdown}': True
  
# Remove the hashtag to specify which version of output you would like.
# Can only choose one at a time.
output:
  # thesisdown::thesis_pdf:
  # latex_engine: xelatex
 # thesisdown::thesis_gitbook: default
  thesisdown::thesis_word:
    reference_docx: "thesis_word_style.docx"
    toc: true
    toc_depth: 3
    fig_caption: true
    lot: true
 # thesisdown::thesis_epub: default
 
header-includes:
- \usepackage[width=\textwidth,justification=raggedright,singlelinecheck=false]{caption}
- \usepackage{array}
# If you are creating a PDF you'll need to write your preliminary content 
# (e.g., abstract, acknowledgements) below or use code similar to line 25-26 
# for the .RMD files. If you are NOT producing a PDF, delete or silence
# lines 25-39 in this YAML header.
abstract: '`r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "00-abstract.Rmd")), collapse = "\n  ")`'

acknowledgements: '`r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "00-acknowledgements.Rmd")), collapse = "\n  ")`'

dedication: |
  Dedicated to my wife and best friend Alli.

attribution: '`r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "00-attribution.Rmd")), collapse = "\n  ")`'
  
# preface: |  
#   This is an example of a thesis setup to use the reed thesis document class 
#   (for LaTeX) and the R bookdown package, in general.

# Specify the location of the bibliography below
bibliography: bib/Zotero_library.bib
# Download your specific csl file and refer to it in the line below.
csl: csl/apa.csl
lot: false
lof: true
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of 
metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete the section entirely, or silence them (add # before each line). 

If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.

If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include=FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if (!require(remotes)) {
  if (params$`Install needed packages for {thesisdown}`) {
    install.packages("remotes", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste('You need to run install.packages("remotes")",
            "first in the Console.')
    )
  }
}
if (!require(thesisdown)) {
  if (params$`Install needed packages for {thesisdown}`) {
    remotes::install_github("ismayc/thesisdown")
  } else {
    stop(
      paste(
        "You need to run",
        'remotes::install_github("ismayc/thesisdown")',
        "first in the Console."
      )
    )
  }
}
library(thesisdown)
# Set how wide the R output will go
options(width = 100)
```

```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00-abstract.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00-acknowledgements.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00-attribution.Rmd")}

```
